.mode csv

-- TODO: create the tables ourselves to encode primary key and foreign key relations
.import '原始資料/kautian-例句.csv'
.import '原始資料/kautian-俗唸作.csv'
.import '原始資料/kautian-又唸作.csv'
.import '原始資料/kautian-合音唸作.csv'
.import '原始資料/kautian-名.csv'
.import '原始資料/kautian-姓.csv'
.import '原始資料/kautian-漢字羅馬字對應.csv'
.import '原始資料/kautian-異用字.csv'
.import '原始資料/kautian-羅馬字清單.csv'
.import '原始資料/kautian-義項.csv'
.import '原始資料/kautian-義項tuì義項反義.csv'
.import '原始資料/kautian-義項tuì義項近義.csv'
.import '原始資料/kautian-義項tuì詞目反義.csv'
.import '原始資料/kautian-義項tuì詞目近義.csv'
.import '原始資料/kautian-詞彙比較.csv'
.import '原始資料/kautian-詞目.csv'
.import '原始資料/kautian-詞目tuì詞目反義.csv'
.import '原始資料/kautian-詞目tuì詞目近義.csv'
.import '原始資料/kautian-語音差異.csv'
